// <auto-generated />
using System;
using CacheScope.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CacheScope.Database.Migrations
{
    [DbContext(typeof(CacheScopeDbContext))]
    partial class CacheScopeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CacheScope.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Books",
                            Name = "Product 001",
                            Price = 8.5m,
                            Stock = 17,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Home",
                            Name = "Product 002",
                            Price = 12.0m,
                            Stock = 24,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Toys",
                            Name = "Product 003",
                            Price = 15.5m,
                            Stock = 31,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Apparel",
                            Name = "Product 004",
                            Price = 19.0m,
                            Stock = 38,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "Grocery",
                            Name = "Product 005",
                            Price = 22.5m,
                            Stock = 45,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = "Sports",
                            Name = "Product 006",
                            Price = 26.0m,
                            Stock = 52,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = "Beauty",
                            Name = "Product 007",
                            Price = 29.5m,
                            Stock = 59,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = "Electronics",
                            Name = "Product 008",
                            Price = 33.0m,
                            Stock = 66,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = "Books",
                            Name = "Product 009",
                            Price = 36.5m,
                            Stock = 73,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 10,
                            Category = "Home",
                            Name = "Product 010",
                            Price = 40.0m,
                            Stock = 80,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 11,
                            Category = "Toys",
                            Name = "Product 011",
                            Price = 43.5m,
                            Stock = 87,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 12,
                            Category = "Apparel",
                            Name = "Product 012",
                            Price = 47.0m,
                            Stock = 94,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 13,
                            Category = "Grocery",
                            Name = "Product 013",
                            Price = 50.5m,
                            Stock = 101,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 14,
                            Category = "Sports",
                            Name = "Product 014",
                            Price = 54.0m,
                            Stock = 108,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 15,
                            Category = "Beauty",
                            Name = "Product 015",
                            Price = 57.5m,
                            Stock = 115,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 16,
                            Category = "Electronics",
                            Name = "Product 016",
                            Price = 61.0m,
                            Stock = 122,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 17,
                            Category = "Books",
                            Name = "Product 017",
                            Price = 64.5m,
                            Stock = 129,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 18,
                            Category = "Home",
                            Name = "Product 018",
                            Price = 68.0m,
                            Stock = 136,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 19,
                            Category = "Toys",
                            Name = "Product 019",
                            Price = 71.5m,
                            Stock = 143,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 20,
                            Category = "Apparel",
                            Name = "Product 020",
                            Price = 75.0m,
                            Stock = 150,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 21,
                            Category = "Grocery",
                            Name = "Product 021",
                            Price = 78.5m,
                            Stock = 157,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 22,
                            Category = "Sports",
                            Name = "Product 022",
                            Price = 82.0m,
                            Stock = 164,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 23,
                            Category = "Beauty",
                            Name = "Product 023",
                            Price = 85.5m,
                            Stock = 171,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 24,
                            Category = "Electronics",
                            Name = "Product 024",
                            Price = 89.0m,
                            Stock = 178,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 25,
                            Category = "Books",
                            Name = "Product 025",
                            Price = 92.5m,
                            Stock = 185,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 26,
                            Category = "Home",
                            Name = "Product 026",
                            Price = 96.0m,
                            Stock = 192,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 27,
                            Category = "Toys",
                            Name = "Product 027",
                            Price = 99.5m,
                            Stock = 199,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 28,
                            Category = "Apparel",
                            Name = "Product 028",
                            Price = 103.0m,
                            Stock = 206,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 29,
                            Category = "Grocery",
                            Name = "Product 029",
                            Price = 106.5m,
                            Stock = 213,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 30,
                            Category = "Sports",
                            Name = "Product 030",
                            Price = 110.0m,
                            Stock = 220,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 31,
                            Category = "Beauty",
                            Name = "Product 031",
                            Price = 113.5m,
                            Stock = 227,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 32,
                            Category = "Electronics",
                            Name = "Product 032",
                            Price = 117.0m,
                            Stock = 234,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 33,
                            Category = "Books",
                            Name = "Product 033",
                            Price = 120.5m,
                            Stock = 241,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 34,
                            Category = "Home",
                            Name = "Product 034",
                            Price = 124.0m,
                            Stock = 248,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 35,
                            Category = "Toys",
                            Name = "Product 035",
                            Price = 127.5m,
                            Stock = 255,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 36,
                            Category = "Apparel",
                            Name = "Product 036",
                            Price = 131.0m,
                            Stock = 262,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 37,
                            Category = "Grocery",
                            Name = "Product 037",
                            Price = 134.5m,
                            Stock = 269,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 38,
                            Category = "Sports",
                            Name = "Product 038",
                            Price = 138.0m,
                            Stock = 276,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 39,
                            Category = "Beauty",
                            Name = "Product 039",
                            Price = 141.5m,
                            Stock = 283,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 40,
                            Category = "Electronics",
                            Name = "Product 040",
                            Price = 145.0m,
                            Stock = 290,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 41,
                            Category = "Books",
                            Name = "Product 041",
                            Price = 148.5m,
                            Stock = 297,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 42,
                            Category = "Home",
                            Name = "Product 042",
                            Price = 152.0m,
                            Stock = 304,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 43,
                            Category = "Toys",
                            Name = "Product 043",
                            Price = 155.5m,
                            Stock = 311,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 44,
                            Category = "Apparel",
                            Name = "Product 044",
                            Price = 159.0m,
                            Stock = 318,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 45,
                            Category = "Grocery",
                            Name = "Product 045",
                            Price = 162.5m,
                            Stock = 325,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 46,
                            Category = "Sports",
                            Name = "Product 046",
                            Price = 166.0m,
                            Stock = 332,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 47,
                            Category = "Beauty",
                            Name = "Product 047",
                            Price = 169.5m,
                            Stock = 339,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 48,
                            Category = "Electronics",
                            Name = "Product 048",
                            Price = 173.0m,
                            Stock = 346,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 49,
                            Category = "Books",
                            Name = "Product 049",
                            Price = 176.5m,
                            Stock = 353,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 50,
                            Category = "Home",
                            Name = "Product 050",
                            Price = 180.0m,
                            Stock = 360,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 51,
                            Category = "Toys",
                            Name = "Product 051",
                            Price = 183.5m,
                            Stock = 367,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 52,
                            Category = "Apparel",
                            Name = "Product 052",
                            Price = 187.0m,
                            Stock = 374,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 53,
                            Category = "Grocery",
                            Name = "Product 053",
                            Price = 190.5m,
                            Stock = 381,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 54,
                            Category = "Sports",
                            Name = "Product 054",
                            Price = 194.0m,
                            Stock = 388,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 55,
                            Category = "Beauty",
                            Name = "Product 055",
                            Price = 197.5m,
                            Stock = 395,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 56,
                            Category = "Electronics",
                            Name = "Product 056",
                            Price = 201.0m,
                            Stock = 402,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 57,
                            Category = "Books",
                            Name = "Product 057",
                            Price = 204.5m,
                            Stock = 409,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 58,
                            Category = "Home",
                            Name = "Product 058",
                            Price = 208.0m,
                            Stock = 416,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 59,
                            Category = "Toys",
                            Name = "Product 059",
                            Price = 211.5m,
                            Stock = 423,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 60,
                            Category = "Apparel",
                            Name = "Product 060",
                            Price = 215.0m,
                            Stock = 430,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 61,
                            Category = "Grocery",
                            Name = "Product 061",
                            Price = 218.5m,
                            Stock = 437,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 62,
                            Category = "Sports",
                            Name = "Product 062",
                            Price = 222.0m,
                            Stock = 444,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 63,
                            Category = "Beauty",
                            Name = "Product 063",
                            Price = 225.5m,
                            Stock = 451,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 64,
                            Category = "Electronics",
                            Name = "Product 064",
                            Price = 229.0m,
                            Stock = 458,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 65,
                            Category = "Books",
                            Name = "Product 065",
                            Price = 232.5m,
                            Stock = 465,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 66,
                            Category = "Home",
                            Name = "Product 066",
                            Price = 236.0m,
                            Stock = 472,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 67,
                            Category = "Toys",
                            Name = "Product 067",
                            Price = 239.5m,
                            Stock = 479,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 68,
                            Category = "Apparel",
                            Name = "Product 068",
                            Price = 243.0m,
                            Stock = 486,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 69,
                            Category = "Grocery",
                            Name = "Product 069",
                            Price = 246.5m,
                            Stock = 493,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 70,
                            Category = "Sports",
                            Name = "Product 070",
                            Price = 250.0m,
                            Stock = 500,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 71,
                            Category = "Beauty",
                            Name = "Product 071",
                            Price = 253.5m,
                            Stock = 507,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 72,
                            Category = "Electronics",
                            Name = "Product 072",
                            Price = 257.0m,
                            Stock = 514,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 73,
                            Category = "Books",
                            Name = "Product 073",
                            Price = 260.5m,
                            Stock = 521,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 74,
                            Category = "Home",
                            Name = "Product 074",
                            Price = 264.0m,
                            Stock = 528,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 75,
                            Category = "Toys",
                            Name = "Product 075",
                            Price = 267.5m,
                            Stock = 535,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 76,
                            Category = "Apparel",
                            Name = "Product 076",
                            Price = 271.0m,
                            Stock = 542,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 77,
                            Category = "Grocery",
                            Name = "Product 077",
                            Price = 274.5m,
                            Stock = 549,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 78,
                            Category = "Sports",
                            Name = "Product 078",
                            Price = 278.0m,
                            Stock = 556,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 79,
                            Category = "Beauty",
                            Name = "Product 079",
                            Price = 281.5m,
                            Stock = 563,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 80,
                            Category = "Electronics",
                            Name = "Product 080",
                            Price = 285.0m,
                            Stock = 570,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 81,
                            Category = "Books",
                            Name = "Product 081",
                            Price = 288.5m,
                            Stock = 577,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 82,
                            Category = "Home",
                            Name = "Product 082",
                            Price = 292.0m,
                            Stock = 584,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 83,
                            Category = "Toys",
                            Name = "Product 083",
                            Price = 295.5m,
                            Stock = 591,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 84,
                            Category = "Apparel",
                            Name = "Product 084",
                            Price = 299.0m,
                            Stock = 598,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 85,
                            Category = "Grocery",
                            Name = "Product 085",
                            Price = 302.5m,
                            Stock = 605,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 86,
                            Category = "Sports",
                            Name = "Product 086",
                            Price = 306.0m,
                            Stock = 612,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 87,
                            Category = "Beauty",
                            Name = "Product 087",
                            Price = 309.5m,
                            Stock = 619,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 88,
                            Category = "Electronics",
                            Name = "Product 088",
                            Price = 313.0m,
                            Stock = 626,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 89,
                            Category = "Books",
                            Name = "Product 089",
                            Price = 316.5m,
                            Stock = 633,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 90,
                            Category = "Home",
                            Name = "Product 090",
                            Price = 320.0m,
                            Stock = 640,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 91,
                            Category = "Toys",
                            Name = "Product 091",
                            Price = 323.5m,
                            Stock = 647,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 92,
                            Category = "Apparel",
                            Name = "Product 092",
                            Price = 327.0m,
                            Stock = 654,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 93,
                            Category = "Grocery",
                            Name = "Product 093",
                            Price = 330.5m,
                            Stock = 661,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 94,
                            Category = "Sports",
                            Name = "Product 094",
                            Price = 334.0m,
                            Stock = 668,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 95,
                            Category = "Beauty",
                            Name = "Product 095",
                            Price = 337.5m,
                            Stock = 675,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 96,
                            Category = "Electronics",
                            Name = "Product 096",
                            Price = 341.0m,
                            Stock = 682,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 97,
                            Category = "Books",
                            Name = "Product 097",
                            Price = 344.5m,
                            Stock = 689,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 98,
                            Category = "Home",
                            Name = "Product 098",
                            Price = 348.0m,
                            Stock = 696,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 99,
                            Category = "Toys",
                            Name = "Product 099",
                            Price = 351.5m,
                            Stock = 703,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = 100,
                            Category = "Apparel",
                            Name = "Product 100",
                            Price = 355.0m,
                            Stock = 710,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
